<a href="https://colab.research.google.com/github/rahulgopigerman17/PytorchPractice/blob/practice1/InitialPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [4]:
torch1 = torch.arange(15)
torch1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
torch2 = torch1.view(3, -1)
torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [22]:
torch3 = torch2[1,-2:]
torch3

tensor([8, 9])